from . import res_partner
from . import product_template
from . import stock_picking
from . import lista_utiles
from . import recepcion_utiles
from . import matricula_escolar
from . import almacen_utiles
from . import salida_almacen_utiles
from . import anio_escolar
from . import periodo_escolar
from . import sobrante_utiles
from . import cierre_anio_utiles
from . import cierre_anio_matriculas
from . import reconocimiento_ia_utiles
from . import recepcion_ia_utiles
from . import product_ia_utiles