from . import res_partner
from . import product_template
from . import stock_picking
from . import lista_utiles
from . import recepcion_utiles
from . import matricula_escolar
from . import almacen_utiles
from . import salida_almacen_utiles
from . import anio_escolar